### ISSUE TITLE
Question about CPU usage

### ISSUE THREAD

**Issue by parkerlreed** [azya52/BrickEmuPy#11]
BrickEmuPy seems to max out a single thread, even with the debugger hidden. 

Is the debugger the cause of this or is the emulation in general causing the "high" usage?

**Comment by azya52** [comment]
Emulation takes up most of the CPU time.
And the main problem, as far as I understand, is that I try to perform each instruction in its own time, as a real processor would do, because of this the CPU has no time to sleep at all. Instead, I need to execute the instructions of the emulated processor in groups, tied not to the clock, but, for example, to the refresh rate of the display. Maybe I'll do it someday.

**Comment by parkerlreed** [comment]
Thank you!
